[workspace]
resolver = "3"
members = ["api", "api-types", "async-brigadier", "worker"]

[workspace.dependencies]
api-types = { path = "api-types" }
fluxer-neptunium = { git = "https://github.com/PilkeySEK/fluxer-neptunium.git", features = [
    "experimental-macros",
    "chrono-timestamp-conversion",
] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "chrono"] }
async-brigadier = { path = "async-brigadier" }

[workspace.lints.clippy]
pedantic = "warn"
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
indexing_slicing = "warn"
string_slice = "warn"
allow_attributes = "warn"
decimal_literal_representation = "warn"
doc_paragraphs_missing_punctuation = "warn"
suspicious = "warn"
branches_sharing_code = "warn"
style = "warn"
perf = "warn"
complexity = "warn"
needless_raw_strings = "warn"
redundant_clone = "warn"
manual_let_else = "warn"
unreadable_literal = { level = "allow", priority = 1 }
str_to_string = "warn"
